### ISSUE TITLE
First milestone suggestion

### ISSUE THREAD

**Issue by luisfarzati** [openunite/openunite#2]
We can think of an MVP that lets you do just enough to make openunite reasonably useful?

Like: "I can setup openunite for my group, create events and let people see the events".

Even without user registration and RSVP, we could say it's still useful because interested people can see the events, their location, and just go. This could be the simplest use case for public events in open venues.

So a high level overview of tasks could be:

1. Initial setup of your instance, using default admin credentials (that are passed via env vars)
2. As a logged-in admin, create a new Event (name, location, description, basic information)
3. As an anonymous user, see the list of Events (past and upcoming)
4. As an anonymous user, see the details for a given Event.

**Comment by alanreid** [comment]
Sounds perfect! 

User authentication & authorization would be a good place to start then, as we'd have three different user levels: admin, registered user, anonymous user.

On the frontend front, this would mean: 

- [ ] Create a registration form
- [ ] Create a login form
- [ ] Create an event creation form
- [ ] Create an event detail page
- [ ] Wire registration form with the API
- [ ] Wire login form with the API
- [ ] Wire event creation form with the API
- [ ] Wire event list page with the API
- [ ] Wire event detail page with the API
- [ ] Handle user state

**Comment by alanreid** [comment]
Now that the GH issues are there, we can just define those features better in each. Closing this one!
